[package]
name = "csv_processor_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
polars = { version = "0.36", features = ["lazy", "csv"] }
rayon = "1.8"
