[package]
name = "rust_csv"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_csv"
crate-type = ["cdylib"]

[dependencies]
csv = "1.2"
serde = { version = "1", features = ["derive"] }
polars = { version = "0.36", features = ["lazy", "csv"] }
rayon = "1.8"
